### ISSUE TITLE
can crystal-helmet be used with kemal?

### ISSUE THREAD

**Issue by carcinocron** [EvanHahn/crystal-helmet#6]
https://kemalcr.com/guide/#middleware

I tried this:
```
In src/app.cr:71:1

 71 | add_handler Helmet::XSSFilterHandler.new,
      ^----------
Error: no overload matches 'add_handler' with types Helmet::XSSFilterHandler, Nil

Overloads are:
 - add_handler(handler : HTTP::Handler, position : Int32)
 - add_handler(handler : HTTP::Handler)
```

**Comment by EvanHahn** [comment]
I haven't tested this module in awhile and I've never tested it with Kemal.

Based on what you've shown, it doesn't look like it works, and this module might need some updating. Is that something you'd be able to help out with?

**Comment by carcinocron** [comment]
I figured it out, this works:

```
add_handler Helmet::DNSPrefetchControllerHandler.new
add_handler Helmet::FrameGuardHandler.new
add_handler Helmet::InternetExplorerNoOpenHandler.new
add_handler Helmet::NoSniffHandler.new
add_handler Helmet::StrictTransportSecurityHandler.new(7.day)
add_handler Helmet::XSSFilterHandler.new
```

Originally I had:
```
add_handler Helmet::XSSFilterHandler.new,
```
and there was a comma because I copied it from the readme, which the compiler suprisingly interpreted as:
```
add_handler(Helmet::XSSFilterHandler.new, nil)
```

**Comment by EvanHahn** [comment]
Glad you figured it out! Let me know if I can help with anything else.
